apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-project-deployment
  labels:
    app: capstone-project-deployment
  namespace: capstone-project
spec:
  replicas: 4
  selector:
    matchLabels:
      app: capstone-project-deployment
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: capstone-project-deployment
    spec:
      containers:
        - image: orinaoisera22/capstone-project
          imagePullPolicy: Always
          name: capstone-project-deployment
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: capstone-project-deployment
  labels:
    app: capstone-project-deployment
spec:
  type: LoadBalancer
  selector:
    app: capstone-project-deployment
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30000
      protocol: TCP
